import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TextInput, TouchableOpacity } from 'react-native';
import { COLORS } from '../../constants/colors';
import { SPACING, LAYOUT } from '../../constants/spacing';
import { TYPOGRAPHY } from '../../constants/typography';
import { PatientCard } from '../../components/cards/PatientCard';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { ErrorView } from '../../components/common/ErrorView';
import { PrimaryButton } from '../../components/buttons/PrimaryButton';
import { usePatient } from '../../hooks/usePatient';
import { useAuth } from '../../hooks/useAuth';
import { PatientService } from '../../services/patient.service';

interface DashboardScreenProps {
  onSelectPatient?: (patientId: string) => void;
}

export const DashboardScreen: React.FC<DashboardScreenProps> = ({ onSelectPatient }) => {
  const { user } = useAuth();
  const { patients, isLoading, error, refetch } = usePatient();
  const [inviteCode, setInviteCode] = useState('');
  const [isLinking, setIsLinking] = useState(false);
  const [linkMessage, setLinkMessage] = useState<string | null>(null);
  const [linkError, setLinkError] = useState<string | null>(null);

  const handleLinkPatient = async () => {
    if (!inviteCode.trim()) {
      setLinkError('Please enter a valid invite code.');
      return;
    }

    setIsLinking(true);
    setLinkMessage(null);
    setLinkError(null);

    const res = await PatientService.joinPatientWithCode(inviteCode);
    setIsLinking(false);

    if (res.success) {
      setLinkMessage('Successfully linked to patient!');
      setInviteCode('');
      refetch();
    } else {
      setLinkError(res.message || 'Invalid or expired invite code.');
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.container} accessibilityLabel="Caregiver Overview Dashboard">
      <Text style={styles.headerTitle}>Caregiver Portal</Text>
      <Text style={styles.subtitle}>Welcome, {user?.name || 'Caregiver'}. Monitoring linked patients.</Text>

      <View style={styles.statsBanner}>
        <View style={styles.statBox}>
          <Text style={styles.statNum}>{patients.length}</Text>
          <Text style={styles.statLabel}>Linked Patients</Text>
        </View>
        <View style={styles.statDivider} />
        <View style={styles.statBox}>
          <Text style={[styles.statNum, { color: COLORS.primary.dark }]}>
            {patients.length > 0 ? 'Active' : 'N/A'}
          </Text>
          <Text style={styles.statLabel}>Health Status</Text>
        </View>
      </View>

      {/* Invite Code Linking Card */}
      <View style={styles.linkCard}>
        <Text style={styles.linkCardTitle}>🔗 Link Patient Account</Text>
        <Text style={styles.linkCardDesc}>
          Enter the 8-character invite code generated by your family member in their CareCompanion app.
        </Text>

        {linkMessage && (
          <View style={styles.successBanner}>
            <Text style={styles.successText}>✅ {linkMessage}</Text>
          </View>
        )}

        {linkError && (
          <View style={styles.errorBanner}>
            <Text style={styles.errorText}>❌ {linkError}</Text>
          </View>
        )}

        <View style={styles.inputRow}>
          <TextInput
            style={styles.codeInput}
            placeholder="e.g. A1B2C3D4"
            value={inviteCode}
            onChangeText={(text) => {
              setInviteCode(text.toUpperCase());
              if (linkError) setLinkError(null);
            }}
            autoCapitalize="characters"
            maxLength={10}
          />
          <TouchableOpacity style={styles.linkBtn} onPress={handleLinkPatient} disabled={isLinking}>
            <Text style={styles.linkBtnText}>{isLinking ? 'Linking...' : 'Connect'}</Text>
          </TouchableOpacity>
        </View>
      </View>

      <Text style={styles.sectionTitle}>Linked Patient Overview</Text>

      {isLoading ? (
        <LoadingSpinner message="Loading patient health summary..." />
      ) : error ? (
        <ErrorView message={error} onRetry={refetch} />
      ) : patients.length === 0 ? (
        <View style={styles.emptyCard}>
          <Text style={styles.emptyIcon}>👥</Text>
          <Text style={styles.emptyTitle}>No Patients Linked Yet</Text>
          <Text style={styles.emptyDesc}>
            Use the invite code box above to connect with your family member's patient account.
          </Text>
        </View>
      ) : (
        patients.map((p) => (
          <PatientCard key={p.id} patient={p} onPress={() => onSelectPatient && onSelectPatient(p.id)} />
        ))
      )}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: SPACING.md,
    backgroundColor: COLORS.neutral.background,
    flexGrow: 1,
  },
  headerTitle: {
    fontSize: TYPOGRAPHY.fontSize.h1,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.neutral.textPrimary,
  },
  subtitle: {
    fontSize: TYPOGRAPHY.fontSize.body,
    color: COLORS.neutral.textSecondary,
    marginBottom: SPACING.lg,
  },
  statsBanner: {
    flexDirection: 'row',
    backgroundColor: COLORS.secondary.light,
    borderRadius: 16,
    padding: SPACING.md,
    alignItems: 'center',
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.secondary.main,
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
  },
  statNum: {
    fontSize: TYPOGRAPHY.fontSize.h1,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.secondary.dark,
  },
  statLabel: {
    fontSize: TYPOGRAPHY.fontSize.caption,
    color: COLORS.neutral.textSecondary,
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: COLORS.neutral.border,
  },
  linkCard: {
    backgroundColor: COLORS.neutral.card,
    borderRadius: LAYOUT.borderRadiusCard,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.neutral.border,
  },
  linkCardTitle: {
    fontSize: TYPOGRAPHY.fontSize.h3,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.neutral.textPrimary,
    marginBottom: SPACING.xs,
  },
  linkCardDesc: {
    fontSize: TYPOGRAPHY.fontSize.body,
    color: COLORS.neutral.textSecondary,
    marginBottom: SPACING.md,
  },
  successBanner: {
    backgroundColor: COLORS.primary.light,
    padding: SPACING.sm,
    borderRadius: 8,
    marginBottom: SPACING.sm,
  },
  successText: {
    color: COLORS.primary.dark,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  errorBanner: {
    backgroundColor: COLORS.error.light,
    padding: SPACING.sm,
    borderRadius: 8,
    marginBottom: SPACING.sm,
  },
  errorText: {
    color: COLORS.error.dark,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  codeInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.neutral.border,
    borderRadius: 8,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    fontSize: TYPOGRAPHY.fontSize.h3,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    letterSpacing: 2,
    backgroundColor: COLORS.neutral.white,
  },
  linkBtn: {
    backgroundColor: COLORS.secondary.main,
    borderRadius: 8,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    marginLeft: SPACING.sm,
  },
  linkBtnText: {
    color: COLORS.neutral.white,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    fontSize: TYPOGRAPHY.fontSize.body,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.fontSize.h3,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.neutral.textPrimary,
    marginBottom: SPACING.md,
  },
  emptyCard: {
    backgroundColor: COLORS.neutral.card,
    borderRadius: LAYOUT.borderRadiusCard,
    padding: SPACING.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.neutral.border,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: SPACING.sm,
  },
  emptyTitle: {
    fontSize: TYPOGRAPHY.fontSize.h2,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.neutral.textPrimary,
    marginBottom: SPACING.xs,
  },
  emptyDesc: {
    fontSize: TYPOGRAPHY.fontSize.body,
    color: COLORS.neutral.textSecondary,
    textAlign: 'center',
  },
});
